services:
  bot: 
    build:
      context: .
      dockerfile: Dockerfile
    image: 'giftbottg:latest'
    networks:
      - telegram
    restart: always
    env_file:
      - ./.env
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
    depends_on:
      - db

  db:
    image: 'postgres:18'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - telegram
    restart: always
    env_file:
      - ./.env

  # ← НОВЫЙ СЕРВИС
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"  # Порт 8080 снаружи, 80 внутри контейнера
    volumes:
      - ./static:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - telegram
    restart: always

volumes: 
  postgres-data:
    external: false

networks:
  telegram: