name: Deploy to Server

on:
  push:
    branches:
      - main  # измените на master, если ваша ветка называется master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/giftbottg
          git pull origin main
          sudo docker compose down
          sudo docker compose up --build -d