name: Deploy Bot and Mini App

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-miniapp:
    name: Build Mini App
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      working-directory: ./miniapp
      run: npm install

    - name: Build Mini App
      working-directory: ./miniapp
      env:
        VITE_API_URL: https://vpnedenor.ru
        VITE_BOT_USERNAME: sofnixrobot
      run: npm run build

    - name: Commit and Push to docs/
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git add docs/
        git diff --quiet && git diff --staged --quiet || (git commit -m "🚀 Auto-deploy Mini App" && git push)

  deploy-bot:
    name: Deploy Bot to Server
    runs-on: ubuntu-latest
    needs: build-miniapp
    permissions:
      contents: read
      packages: write
      id-token: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ghcr.io/pprly/giftbottg:latest

    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/giftbottg
